// GENERATED by `make types` from backend/premarket/models.py. Do not edit.

export interface Stat {
  value: number | null;
  n: number;
  from: string | null;
  to: string | null;
  unit: string;
}

export interface SourceHealth {
  ok: boolean;
  as_of: string | null;
  delay_min: number | null;
  error: string | null;
  source: string;
}

export interface Meta {
  instrument: string;
  instrument_name: string;
  contract: string;
  contract_long: string;
  contract_expiry: string;
  contract_roll: string;
  days_to_roll: number;
  days_to_expiry: number;
  expiring_contract: string | null;
  expiring_in_days: number | null;
  generated_at: string;
  trading_date: string;
  weekday: string;
  anchor: string;
  window: Record<string, string>;
  milestones: string[];
  health: Record<string, SourceHealth>;
  data_source: string;
  price_delay_min: number | null;
  roll_warning: string | null;
  tick: number;
}

export interface Brief {
  today: string;
  bias: string;
  watch: string;
}

export interface Price {
  last: number | null;
  as_of: string | null;
  delay_min: number | null;
  vs_prev_close: number | null;
  vs_midnight_open: number | null;
  vs_daily_open: number | null;
}

export interface Range {
  h: number | null;
  l: number | null;
  o: number | null;
  c: number | null;
  eq: number | null;
  start: string | null;
  end: string | null;
}

export interface LevelRow {
  id: string;
  name: string;
  price: number;
  distance: number;
  state: "untested" | "swept";
  swept_at: string | null;
  kind: string;
}

export interface Levels {
  pdh: number | null;
  pdl: number | null;
  pdc: number | null;
  pwh: number | null;
  pwl: number | null;
  daily_open: number | null;
  midnight_open: number | null;
  open_0830: number | null;
  open_0900: number | null;
  open_0930: number | null;
  weekly_open: number | null;
  monthly_open: number | null;
  sessions: Record<string, Range>;
  above: LevelRow[];
  below: LevelRow[];
}

export interface SessionStat {
  range: number | null;
  avg20: Stat;
  pct_of_avg: number | null;
  start: string | null;
  end: string | null;
  direction: string | null;
}

export interface Sweep {
  side: "high" | "low";
  at: string;
  depth_ticks: number;
  pct: number;
  key_time: boolean;
  closed_inside: boolean | null;
  reclaimed_at: string | null;
  candle_close_at: string | null;
  extreme: number;
  reclaim_candles: number;
}

export interface TFState {
  phase: "range" | "manipulation" | "manipulation_confirmed" | "distribution" | "complete" | "expansion" | "invalidated";
  sweeps: Sweep[];
}

export interface ContextRange {
  id: string;
  label: string;
  kind: "context" | "session" | "execution";
  timeframe: string | null;
  o: number | null;
  h: number | null;
  l: number | null;
  c: number | null;
  eq: number | null;
  start: string | null;
  end: string | null;
  live: boolean;
  sweeps: Sweep[];
  phase: "range" | "manipulation" | "manipulation_confirmed" | "distribution" | "complete" | "expansion" | "invalidated";
  readable: boolean;
  reached_eq_at: string | null;
  reached_opposite_at: string | null;
  invalidated_at: string | null;
  by_timeframe: Record<string, TFState>;
}

export interface ExecutionTF {
  timeframe: "15m" | "30m" | "1h";
  range: ContextRange | null;
  state: "pending" | "confirmed" | "active" | "done" | "invalidated" | "watch" | null;
  closes_at: string | null;
  sequence_phase: string;
  note: string;
}

export interface Odds {
  reach_eq: Stat;
  reach_opposite: Stat;
  invalidated: Stat;
  close_inside_given_sweep: Stat;
  median_min_to_t1: Stat;
  median_min_to_t2: Stat;
}

export interface Setup {
  id: string;
  timeframe: "15m" | "30m" | "1h";
  template: string;
  scenario: "primary" | "alternate" | "counter";
  state: "pending" | "confirmed" | "active" | "done" | "invalidated" | "watch";
  direction: "long" | "short";
  range_id: string;
  range_label: string;
  sweep_side: "high" | "low";
  sweep_level: number;
  sweep_at: string | null;
  reclaim_at: string | null;
  candle_close_at: string | null;
  earliest_entry_at: string | null;
  trigger: string;
  confirmation: string;
  entry_zone: number[];
  entry_note: string;
  stop: number;
  t1: number;
  t2: number;
  t3: number | null;
  rr_t2: number | null;
  quality: number;
  quality_reasons: string[];
  odds: Odds;
  odds_scope: string;
  valid_until: string;
  invalidation: string;
  smt: Record<string, any> | null;
  premium_discount: string | null;
  counter_bias: boolean;
  warning: string | null;
  sentence: string;
}

export interface SMT {
  pair: string;
  tiebreak: string | null;
  divergent: boolean;
  side: "high" | "low" | null;
  at: string | null;
  detail: string;
}

export interface Template {
  id: string;
  name: string;
  definition: string;
  live: boolean;
  state: string;
  hit_rate: Stat;
  by_weekday: Record<string, Stat>;
}

export interface CRT {
  context: ContextRange[];
  execution: Record<string, ExecutionTF>;
  setups: Setup[];
  smt: SMT | null;
  premium_discount: Record<string, string>;
  liquidity: LevelRow[];
  templates: Template[];
  atr: Record<string, number | null>;
  as_of: string | null;
}

export interface Factor {
  id: string;
  label: string;
  score: number;
  weight: number;
  weight_raw: number;
  source: "evidence" | "heuristic";
  condition: string | null;
  p_hat: number | null;
  n: number | null;
  reason: string;
  inputs: Record<string, any>;
}

export interface Excluded {
  id: string;
  label: string;
  why: string;
}

export interface Modifier {
  id: string;
  penalty: number;
  reason: string;
}

export interface Scenario {
  name: string;
  direction: "long" | "short";
  trigger: string;
  confirmation: string;
  entry_zone: string;
  target: string;
  invalidation: string;
  valid: string;
  setup_id: string | null;
}

export interface SimilarMornings {
  n: number;
  up: number;
  down: number;
  median_move: number | null;
  reached_pdh: number;
  reached_pdl: number;
  dates: string[];
  text: string;
}

export interface Bias {
  label: "Bullish" | "Bearish" | "Neutral";
  score: number;
  confidence: number;
  confidence_raw: number;
  confidence_math: string;
  factors: Factor[];
  excluded: Excluded[];
  modifiers: Modifier[];
  similar_mornings: SimilarMornings | null;
  narrative: string;
  narrative_source: string;
  scenarios: Record<string, Scenario | null>;
  no_trade: string[];
  flip_if: string[];
  thresholds: Record<string, number>;
  agreement_penalty: number;
}

export interface RatingReason {
  id: string;
  tier: "no_trade" | "caution" | "trade";
  text: string;
}

export interface Rating {
  label: "Trade" | "Caution" | "No trade";
  top_reason: string;
  reasons: RatingReason[];
  plan: string;
  rules_checked: string[];
}

export interface CalEventOut {
  date: string;
  time: string | null;
  when: string | null;
  name: string;
  impact: "high" | "medium" | "low" | "holiday";
  currency: string;
  consensus: string | null;
  previous: string | null;
  actual: string | null;
  in_window: boolean;
}

export interface DayCard {
  date: string;
  weekday: string;
  label: "Trade" | "Caution" | "No trade";
  reasons: string[];
  events: CalEventOut[];
  structural: Record<string, any>[];
  stats: Record<string, Stat>;
  is_today: boolean;
  rank: number | null;
}

export interface Calendar {
  today: CalEventOut[];
  week: DayCard[];
  month: DayCard[];
  structural: Record<string, any>;
  as_of: string | null;
}

export interface HeadlineOut {
  title: string;
  url: string;
  published: string | null;
  source: string;
  feed_id: string;
  relevance: number;
  tags: string[];
  sentiment: "bullish" | "bearish" | "neutral";
  why: string | null;
  pinned: boolean;
}

export interface News {
  summary: string;
  summary_source: string;
  movers: string[];
  movers_source: string;
  headlines: HeadlineOut[];
  groups: Record<string, HeadlineOut[]>;
  feeds: Record<string, any>[];
  sentiment_score: number | null;
  as_of: string | null;
}

export interface IntermarketRow {
  symbol: string;
  name: string;
  last: number | null;
  chg_since_1700: number | null;
  chg_since_midnight: number | null;
  pct_since_1700: number | null;
  sparkline: number[];
  read: string;
  as_of: string | null;
}

export interface Intermarket {
  rows: IntermarketRow[];
  real_yield: Record<string, any> | null;
  breakeven: Record<string, any> | null;
  as_of: string | null;
}

export interface Stats {
  weekday_window: Record<string, any>;
  crt: Record<string, any>;
  lookback: Record<string, any>;
}

export interface Snapshot {
  meta: Meta;
  brief: Brief;
  price: Price;
  levels: Levels;
  sessions: Record<string, SessionStat>;
  crt: CRT;
  bias: Bias;
  rating: Rating;
  ideas: Setup[];
  calendar: Calendar;
  news: News;
  intermarket: Intermarket;
  stats: Stats;
  key_times: Record<string, any>[];
  chart: Record<string, any>;
}

export interface JournalDay {
  date: string;
  instrument: string;
  notes: string;
  checklist: Record<string, boolean>;
  grade: Record<string, any> | null;
}

