"""Generate frontend/src/types/snapshot.ts from the pydantic models (JSON schema → TS)."""

from __future__ import annotations

from typing import Any

from . import models

ORDER = [
    "Stat",
    "SourceHealth",
    "Meta",
    "Brief",
    "Price",
    "Range",
    "LevelRow",
    "Levels",
    "SessionStat",
    "Sweep",
    "TFState",
    "ContextRange",
    "ExecutionTF",
    "Odds",
    "Setup",
    "SMT",
    "Template",
    "CRT",
    "Factor",
    "Excluded",
    "Modifier",
    "Scenario",
    "SimilarMornings",
    "Bias",
    "RatingReason",
    "Rating",
    "CalEventOut",
    "DayCard",
    "Calendar",
    "HeadlineOut",
    "News",
    "IntermarketRow",
    "Intermarket",
    "Stats",
    "Snapshot",
    "JournalDay",
]


def ts_type(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(s, defs) for s in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(f'"{v}"' if isinstance(v, str) else str(v) for v in schema["enum"])
    if "const" in schema:
        return f'"{schema["const"]}"'
    t = schema.get("type")
    if t == "string":
        return "string"
    if t in ("number", "integer"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        inner = ts_type(schema.get("items", {}), defs) if schema.get("items") else "unknown"
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if t == "object":
        if "additionalProperties" in schema and isinstance(schema["additionalProperties"], dict):
            return f"Record<string, {ts_type(schema['additionalProperties'], defs)}>"
        return "Record<string, any>"
    return "any"


def generate() -> str:
    out = ["// GENERATED by `make types` from backend/premarket/models.py. Do not edit.", ""]
    root = models.Snapshot.model_json_schema(by_alias=True, mode="serialization")
    defs = dict(root.get("$defs", {}))
    defs["Snapshot"] = {k: v for k, v in root.items() if k != "$defs"}
    jd = models.JournalDay.model_json_schema(by_alias=True)
    defs["JournalDay"] = {k: v for k, v in jd.items() if k != "$defs"}
    for name in ORDER:
        d = defs.get(name)
        if not d:
            continue
        out.append(f"export interface {name} {{")
        # serialized snapshots always carry every field, so nothing is optional
        for prop, sch in d.get("properties", {}).items():
            out.append(f"  {prop}: {ts_type(sch, defs)};")
        out.append("}")
        out.append("")
    return "\n".join(out)
